#!/usr/bin/env python3
import sys
import os
import shutil

os.chdir(os.path.realpath("/".join(sys.argv[0].split("/")[:-1])))

try:
    os.system("{} main.py".format(shutil.which("python3")))
except KeyboardInterrupt:
    pass
