ModalView:
    background_color:0,0,0,0
    RelativeLayout:
        md_bg_color:0,0,0,.4
        MDLabel:
            id:text_main
            text:"Checking ..."
            halign:"center"
            font_name:app.medium_font
            font_size:"30sp"
            pos_hint:{"center_y":0.7}
        MDSpinner:
            id:spinner
            active:True
            size_hint:None,None
            size:[dp(50)] * 2
            pos_hint:{"center_y":0.5,"center_x":0.5}

